---
apiVersion: v1
kind: Service
metadata:
  name: oci-reader-lb
  namespace: oci-reader-test
  annotations:
    oci.oraclecloud.com/load-balancer-type: "lb"
spec:
  selector:
    app: oci-reader
  type: LoadBalancer
  ports:
    - name: frontend
      port: 80
      targetPort: 3000
      protocol: TCP
    - name: backend
      port: 4000
      targetPort: 4000
      protocol: TCP
